### ISSUE TITLE
(MacOS) Make sure the audio file is in the mapset folder or try moving the osr2mp4 folder to somewhere else because the current path might have some special characters.

### ISSUE THREAD

**Issue by brickyosu** [uyitroa/osr2mp4-core#102]
bruh i set mac osu folder in ./Desktop/osu!.app/Contents/Resources/drive_c/osu! and output in ./Movies and then this popped up. i did all the installing instructions BUT this keeps happening when i am tryna convert .osr file to mp4, i need help please.

**Comment by uyitroa** [comment]
send logs

**Comment by brickyosu** [comment]
> send logs

/Users/dax/pythonapps/osr2mp4-app/main.py:172: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  self.resize(self.width(), height)
Updated
QSoundEffect(qaudio): Error decoding source file:blank

**Comment by uyitroa** [comment]
can you zip all logs and send it

**Comment by brickyosu** [comment]
> can you zip all logs and send it

[](url)

**Comment by uyitroa** [comment]
Run the app,
Click start, wait for the error to appear.
Then right click on the Logs folder, choose compress.
Send the compressed folder here.

**Comment by brickyosu** [comment]
> Run the app,
> Click start, wait for the error to appear.
> Then right click on the Logs folder, choose compress.
> Send the compressed folder here.

[Logs.zip](https://github.com/uyitroa/osr2mp4-core/files/6704187/Logs.zip)

**Comment by uyitroa** [comment]
do `brew install zlib jpeg freetype xz ffmpeg` in terminal.
What does it print?

**Comment by brickyosu** [comment]
> do `brew install zlib jpeg freetype xz ffmpeg` in terminal.
> What does it print?

hmm
when i did it it took a long time
btw i closed that terminal tab so ima reinstall ig

**Comment by uyitroa** [comment]
do `brew install ffmpeg`

**Comment by brickyosu** [comment]
> do `brew install ffmpeg`

did the same, error downloading theora.

**Comment by uyitroa** [comment]
https://evermeet.cx/ffmpeg/ffmpeg-102787-gec8e95296e.7z

Download this,
Unzip it, then put the file `ffmpeg` in osr2mp4 folder then run the app again.

**Comment by brickyosu** [comment]
ok!

**Comment by brickyosu** [comment]
> https://evermeet.cx/ffmpeg/ffmpeg-102787-gec8e95296e.7z
> 
> Download this,
> Unzip it, then put the file `ffmpeg` in osr2mp4 folder then run the app again.

does not work,

`/Users/dax/pythonapps/osr2mp4-app/main.py:172: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  self.resize(self.width(), height)
Updated
QSoundEffect(qaudio): Error decoding source file:blank
objc[94819]: Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fffa6ebbcd0) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x11f917cd8). One of the two will be used. Which one is undefined.

`

**Comment by brickyosu** [comment]
> > https://evermeet.cx/ffmpeg/ffmpeg-102787-gec8e95296e.7z
> > Download this,
> > Unzip it, then put the file `ffmpeg` in osr2mp4 folder then run the app again.
> 
> does not work,
> 
> `/Users/dax/pythonapps/osr2mp4-app/main.py:172: DeprecationWarning: an integer is required (got type float). Implicit conversion to integers using **int** is deprecated, and may be removed in a future version of Python.
> self.resize(self.width(), height)
> Updated
> QSoundEffect(qaudio): Error decoding source file:blank
> objc[94819]: Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fffa6ebbcd0) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x11f917cd8). One of the two will be used. Which one is undefined.
> 
> `



> https://evermeet.cx/ffmpeg/ffmpeg-102787-gec8e95296e.7z
> 
> Download this,
> Unzip it, then put the file `ffmpeg` in osr2mp4 folder then run the app again.

wait a min, install.py does this:
`skipping 'ccurves.cpp' Cython extension (up-to-date)

Done compiling ccurves module. osr2mp4 should run properly now.

Trying to compile optional feature ffmpeg video writer...
running build_ext
skipping 'PyFrameWriter.cpp' Cython extension (up-to-date)
building 'osr2mp4cv' extension
clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Iinclude -I/Users/dax/.brew/lib/python3.9/site-packages/numpy/core/include -I/Users/dax/.brew/include -I/Users/dax/.brew/opt/openssl@1.1/include -I/Users/dax/.brew/opt/sqlite/include -I/Users/dax/.brew/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c FrameWriter.cpp -o build/temp.macosx-10.13-x86_64-3.9/FrameWriter.o -std=c++11 -w
clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Iinclude -I/Users/dax/.brew/lib/python3.9/site-packages/numpy/core/include -I/Users/dax/.brew/include -I/Users/dax/.brew/opt/openssl@1.1/include -I/Users/dax/.brew/opt/sqlite/include -I/Users/dax/.brew/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c PyFrameWriter.cpp -o build/temp.macosx-10.13-x86_64-3.9/PyFrameWriter.o -std=c++11 -w
clang++ -bundle -undefined dynamic_lookup build/temp.macosx-10.13-x86_64-3.9/FrameWriter.o build/temp.macosx-10.13-x86_64-3.9/PyFrameWriter.o -Llib -L/Users/dax/.brew/lib -L/Users/dax/.brew/opt/openssl@1.1/lib -L/Users/dax/.brew/opt/sqlite/lib -lavcodec -lavutil -lavformat -lswresample -lswscale -o /Users/dax/.brew/lib/python3.9/site-packages/osr2mp4/VideoProcess/FFmpegWriter/osr2mp4cv.cpython-39-darwin.so
ld: library not found for -lavcodec
clang: error: linker command failed with exit code 1 (use -v to see invocation)
error: command '/usr/bin/clang++' failed with exit code 1
Traceback (most recent call last):
  File "/Users/dax/pythonapps/osr2mp4-app/install.py", line 35, in <module>
    subprocess.check_call([sys.executable, "setup.py", "build_ext", "--inplace"])
  File "/Users/dax/.brew/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/Users/dax/.brew/opt/python@3.9/bin/python3.9', 'setup.py', 'build_ext', '--inplace']' returned non-zero exit status 1.`

**Comment by uyitroa** [comment]
you are using python3.9, you need python3.7.8 to work.

**Comment by uyitroa** [comment]
also what error are you getting when clicking start? Still "make sure audio file is blabla"?

**Comment by brickyosu** [comment]
> also what error are you getting when clicking start? Still "make sure audio file is blabla"?

make sure audio file is in mapset folder

**Comment by brickyosu** [comment]
> you are using python3.9, you need python3.7.8 to work.

when I do the pyenv init thingy it does not work. i use bash_profile.

**Comment by uyitroa** [comment]
> when I do the pyenv init thingy it does not work. i use bash_profile.
> 
> 
> 
> 

what? what does not work? 

did you use pyenv to install python or did you install python manually?
If you followed correctly the tutorial you should have installed python3.7.8, not python3.9.

Well you can just uninstall pyenv then download python3.7.8 and install it manually which will be easier. (Just search python on google then click on the first link, then choose python version 3.7.8 then download and install it).

Also repeat this:
> Run the app,
> Click start, wait for the error to appear.
> Then right click on the Logs folder, choose compress.
> Send the compressed folder here.

**Comment by brickyosu** [comment]
> > when I do the pyenv init thingy it does not work. i use bash_profile.
> 
> what? what does not work?
> 
> did you use pyenv to install python or did you install python manually?
> If you followed correctly the tutorial you should have installed python3.7.8, not python3.9.
> 
> Well you can just uninstall pyenv then download python3.7.8 and install it manually which will be easier. (Just search python on google then click on the first link, then choose python version 3.7.8 then download and install it).
> 
> Also repeat this:
> 
> > Run the app,
> > Click start, wait for the error to appear.
> > Then right click on the Logs folder, choose compress.
> > Send the compressed folder here.

wait, when I put in ```
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init --path)"
```
to bash_profile, it just says

`WARNING: `pyenv init -` no longer sets PATH.
Run `pyenv init` to see the necessary changes to make to your configuration.`

**Comment by uyitroa** [comment]
do you have discord or something like that? It will be much easier to debug and fix the issue. Also can you zip the logs folder and send it

**Comment by brickyosu** [comment]
> do you have discord or something like that? It will be much easier to debug and fix the issue. Also can you zip the logs folder and send it

my dad install discord but me is a kid

I looked it up at it say 13+

[Logs.zip](https://github.com/uyitroa/osr2mp4-core/files/6712233/Logs.zip)

**Comment by brickyosu** [comment]
> > when I do the pyenv init thingy it does not work. i use bash_profile.
> 
> what? what does not work?
> 
> did you use pyenv to install python or did you install python manually?
> If you followed correctly the tutorial you should have installed python3.7.8, not python3.9.
> 
> Well you can just uninstall pyenv then download python3.7.8 and install it manually which will be easier. (Just search python on google then click on the first link, then choose python version 3.7.8 then download and install it).
> 
> Also repeat this:
> 
> > Run the app,
> > Click start, wait for the error to appear.
> > Then right click on the Logs folder, choose compress.
> > Send the compressed folder here.

btw I'm not admin on this macintosh

**Comment by uyitroa** [comment]
did you put `ffmpeg` in osr2mp4 folder?

**Comment by uyitroa** [comment]
If it still doesn't work. Follow these steps:
Put `ffmpeg` file back to Downloads folder.
Open terminal, do
```cd ~/Downloads/```
then ```sudo mkdir -p /usr/local/bin/``` 
(you might need to enter the password, also when you type the password, nothing will be shown in the terminal but you can still type it.)
Then do:
```sudo cp ./ffmpeg /usr/local/bin```
after that, you do:
```sudo chmod ugo+x /usr/local/bin/ffmpeg```

after that, ```open -e ~/.bash_profile```

then add this to the file at the end:
```export PATH="/usr/local/bin:$PATH"```

Then restart terminal.

Now you need to reinstall python because you installed the wrong python version,
```brew uninstall pyenv```
```brew uninstall python```

Then download the right version here: https://www.python.org/ftp/python/3.7.8/python-3.7.8-macosx10.9.pkg
Install it. Then restart your pc.
Then redo "Configuring and Running PyEnv and osr2mp4" starting from step 4.

**Comment by brickyosu** [comment]
> If it still doesn't work. Follow these steps:
> Put `FFmpeg file back to Downloads folder.
> Open terminal, do
> `cd ~/Downloads/`
> then `sudo mkdir -p /usr/local/bin/`
> (you might need to enter the password, also when you type the password, nothing will be shown in the terminal but you can still type it.)
> Then do:
> `sudo cp ./ffmpeg /usr/local/bin`
> after that, you do:
> `sudo chmod ugo+x /usr/local/bin/ffmpeg`
> 
> after that, `open -e ~/.bash_profile`
> 
> then add this to the file at the end:
> `export PATH="/usr/local/bin:$PATH"`
> 
> Then restart terminal.
> 
> Now you need to reinstall python because you installed the wrong python version,
> `brew uninstall pyenv`
> `brew uninstall python`
> 
> Then download the right version here: https://www.python.org/ftp/python/3.7.8/python-3.7.8-macosx10.9.pkg
> Install it. Then restart your pc.
> Then redo "Configuring and Running PyEnv and osr2mp4" (of MacOSLinuxInstall.md" starting from step 4.

I'm not a sudoer in the sudoers file, and I am on high sierra and don't have admin perms since my mom is strict and she won't let me download "viruses" on my computer though it isn't a virus.

**Comment by uyitroa** [comment]
sorry osr2mp4 is 13+

**Comment by brickyosu** [comment]
> > my dad install discord but me is a kid
> 
> > I looked it up and it say 13+
> 
> sorry osr2mp4 is 13+

noooooooooooo



now wut do i do :(
