### ISSUE TITLE
Sliders get cut if outside playfield

### ISSUE THREAD

**Issue by asdfgh110** [uyitroa/osr2mp4-core#103]
![Example](https://user-images.githubusercontent.com/88080558/127285654-cb64a6c8-616e-42e0-9445-1e545b8fb6f5.png)
Any way to fix this?

**Comment by uyitroa** [comment]
update ur app

**Comment by asdfgh110** [comment]
Updated the app, sliders don't get cut! Thanks! Feeling stupid rn
