### ISSUE TITLE
Relax plays do not export properly

### ISSUE THREAD

**Issue by DJYoloSwag07** [uyitroa/osr2mp4-core#25]
Steps to reproduce:
Choose a replay with the relax mod in the config file.
The bug will occur with any relax play.

What happens:
The video shows a 0% accuracy full miss replay, as if no keys had been pressed during the playthrough.

Did this work on a previous version?
No

Additional information:
When the replay is opened in game, the 300s/100s/50s/misses are displayed but they show up as zeroes in the console osr2mp4 is launched in.

**Comment by uyitroa** [comment]
why do you play with relax brooo

Jokes aside thanks for testing. I fixed it.
