### ISSUE TITLE
Score is more than expected.

### ISSUE THREAD

**Issue by Hazuki-san** [uyitroa/osr2mp4-core#40]
The score glitch starts at 1:44 

**### Additional information:**
Video: https://www.youtube.com/watch?v=PCOAObgicxE
Replay: https://gofile.io/d/uVZAyR
Beatmap: https://osu.ppy.sh/s/1187071

**Comment by Hazuki-san** [comment]
Some how the replay in osr2mp4-core got more score than the actual osu! that's the reason why the score is not updating.

**Comment by Hazuki-san** [comment]
This might cause by #33

**Comment by uyitroa** [comment]
Indeed. osu!'s spinner are hard to reproduce.

**Comment by uyitroa** [comment]
By the way, is the cursor in the video behaving correctly?

**Comment by Hazuki-san** [comment]
No, the cursor caused by my custom driver
