### ISSUE TITLE
TypeError Help

### ISSUE THREAD

**Issue by Defywastaken** [uyitroa/osr2mp4-core#44]
![image](https://user-images.githubusercontent.com/65021561/88122763-1ef92000-cb65-11ea-8c8a-5cdf9021d16b.png)
Hello, I have an issue where the error message says:
"TypeError("VideoWriter_fourcc()
missing required argument 'c4' (pos4)"

How do you fix this?

**Comment by uyitroa** [comment]
You need to enter the "four character code" for your preferred codec. For example, the fourcc of vp9 is vp90.
You can try to find the fourcc of the codec here: https://www.fourcc.org/codecs.php
