### ISSUE TITLE
Cannot enable FFmpeg Writer

### ISSUE THREAD

**Issue by Ameliaaaaaa** [uyitroa/osr2mp4-core#63]
After going through all the stuff in the master repo, I cannot enable FFMPEG writer as `python setup build_ext --inplace` cannot find the file.

**Comment by uyitroa** [comment]
oops I made a typo, it's setup.py instead of setup

**Comment by Ameliaaaaaa** [comment]
Thanks, it seems to work without it anyways. Probs still needed.
