### ISSUE TITLE
No module named 'osr2mp4.ImageProcess.Curves.libcurves.ccurves'

### ISSUE THREAD

**Issue by coverosu** [uyitroa/osr2mp4-core#81]
I could never wrap my head around this issue. Looked up ways to fix these types of issues, but haven't seen a proper one so I thought I would bring it up.

**Comment by christopher-dG** [comment]
Did you follow the install instructions?

**Comment by coverosu** [comment]
Many times I've followed the instructions, but always end up in the same spot like I am now.

**Comment by christopher-dG** [comment]
Provide some more info and perhaps we can figure it out. What OS are you on? Can you give us the exact sequence of commands you're running and the code you're trying to run?

**Comment by coverosu** [comment]
well I'm on windows 10 and all I'm doing is importing the class 'Osr2mp4', but error pops up when importing. When it comes to the commands I just did the following 
```
cd osr2mp4/
python install.py
pip install cython
cd ImageProcess/Curves/libcurves/
python setup.py build_ext --inplace
cd ..
cd .. 
cd ..
cd VideoProcess/FFmpegWriter/
python setup build_ext --inplace
```
And installed pillow and ffmpeg with no problems. Maybe it could be py on my pc having problems, but I likely doubt it.

**Comment by uyitroa** [comment]
What does it print when you do 

```
cd ImageProcess/Curves/libcurves/
python setup.py build_ext --inplace ```

**Comment by coverosu** [comment]
Soooo, I kind of just reinstalled python and it works properly now. Thanks for the help though, really appreciate it.
