### ISSUE TITLE
Weird problem when converting

### ISSUE THREAD

**Issue by SolarSunrise1** [uyitroa/osr2mp4-core#93]
Not sure if I've done something wrong, but I whenever I try to convert a video in 1080p 240 FPS, the video acts stangely. The hitsounds are higher pitched for the beginning, and after a few slight lagspikes it looks like the video is put in half speed, while the audio still stays the original speed. So the video and audio don't match at all, there are some weird artifacts in the video, and the sound is higher pitched/distorted

**Comment by uyitroa** [comment]
@SolarSunrise1 your pc can't handle high fps you just need to resample the video. There are many tutorials on youtube for that

**Comment by SolarSunrise1** [comment]
I have a GTX 1070 and ryzen 5 2600 16 gb ram, its not like I have a really low spec PC. Do I need to change the encoder or something

**Comment by uyitroa** [comment]
@SolarSunrise1 you are not supposed to watch raw high fps video. You need to resample down to 60 fps first.
